services:
  postgres:
    image: postgres:16
    container_name: dbm_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-55432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-metrics}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-metrics_pass}
      POSTGRES_DB: ${POSTGRES_DB:-metrics_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-metrics} -d ${POSTGRES_DB:-metrics_db} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Prometheus (зберігає метрики у своїй TSDB)
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: dbm_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - promdata:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - pg_exporter

  # Grafana
  grafana:
    image: grafana/grafana:11.2.0
    container_name: dbm_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - grafanadata:/var/lib/grafana

  # Postgres Exporter (віддає метрики Prometheus'у)
  pg_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: dbm_pg_exporter
    restart: unless-stopped
    environment:
      # Підключається ДО postgres по внутрішньому DNS і тим же кредам
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER:-metrics}:${POSTGRES_PASSWORD:-metrics_pass}@postgres:5432/${POSTGRES_DB:-metrics_db}?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "9187:9187"   # опціонально, щоб дивитись з хоста

volumes:
  pgdata:
  promdata:
  grafanadata:
